### ISSUE TITLE
Incorrectly switches closing punctuation only when removing characters

### ISSUE THREAD

**Issue by FichteFoll** [predragnikolic/JS-Template-String-Converter#1]
Deleting a single character between the end of an interpolated block and the closing punctuation incorrectly switches the closing punctuation to a normal quotation symbol (generally `'`).

1. Have this in a JS view with the caret immediately before the end of the template literal: `` `this is ${a string}  ` ``.
2. Hit backspace once.
3. Hit backspace again.

You now have `` `this is ${a string}' `` when it should be `` `this is ${a string}` ``.

Also reproduces with the delete key from the other side (after the interpolated block).

**Comment by predragnikolic** [comment]
Thanks for reporting!
Noticed this as well.

**Comment by FichteFoll** [comment]
Ah, I also just checked that this happens at the other side of the string, i.e. at the beginning, too, if you haven't noticed that yet (I haven't).

**Comment by predragnikolic** [comment]
I pushed a commit, 
the bug was caused by this line:
```
def get_backtick_string_region(view: sublime.View, point: int) -> Optional[sublime.Region]:
    return view.expand_to_scope(point, "string.quoted.other")
```

The `get_backtick_string_region` returned a region that I didn't expect, and that is this region:
```js
//> | is the cursor
let x = `this is ${a string}  |`
                            ^^^^ string.quoted.other
```

I expected the to match this:
```js
let x = `this is ${a string}  |`
         ^^^^^^^^^^^^^^^^^^^^^^^ string.quoted.other
```

the reason for why it didn't match is that the middle part has a different scope"
```js
let x = `this is ${a string}  |`
                 ^^^^^^^^^^^ meta.interpolation
```


I push a fix for it, but a more proper fix would be to update the selector so it returns the region I expect. 
I am pretty bad with how scopes work in ST. Do you know how I could write such selector?

```diff
 - view.expand_to_scope(point, "string.quoted.other")
 + view.expand_to_scope(point, "string.quoted.other | string.quoted.other + meta.interpolation")
```

**Comment by FichteFoll** [comment]
Most modern syntax definitions use `meta.string` as the overarching scope for (interpolated) strings, consisting of one or multiple `string.?` and `meta.interpolation` blocks. This is also the case for JS and TS. 

The selector you're looking for thus is most likely going to be `meta.string`.

However, I see that the latest commit removes this functionality entirely, so it's probably not relevant anymore. It's auto-fixable by eslint anyway, iirc.

**Comment by predragnikolic** [comment]
> However, I see that the latest commit removes this functionality entirely, so it's probably not relevant anymore. It's auto-fixable by eslint anyway, iirc.

Yes, the functionality is removed.
It is fixable by eslint as you mentioned.
